/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Code.Kata

class App {
    fun greeting(): String {
        return "hello dev!"
    }
}

fun main() {
    val app = App()
    println(app.greeting())
}
